$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

require 'shared_context'

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
  config.include_context 'connection setup'
end

require 'cloudflair'
require 'cloudflair/entity'
require 'cloudflair/connection'
require 'cloudflair/communication'
require 'cloudflair/error/cloudflare_error'
require 'cloudflair/error/cloudflair_error'
require 'cloudflair'
require 'cloudflair/api'
require 'cloudflair/api/railguns'
require 'cloudflair/api/zone'
require 'cloudflair/api/zone/analytics'
require 'cloudflair/api/zone/available_plan'
require 'cloudflair/api/zone/available_rate_plan'
require 'cloudflair/api/zone/dns_record'
require 'cloudflair/api/zone/purge_cache'
require 'cloudflair/api/zone/railgun'
require 'cloudflair/api/zone/settings'
require 'cloudflair/api/zone/settings/advanced_ddos'
require 'cloudflair/api/zone/settings/always_online'
require 'cloudflair/api/zone/settings/browser_cache_ttl'
require 'cloudflair/api/zone/settings/cache_level'
require 'cloudflair/api/zone/settings/challenge_ttl'
require 'cloudflair/api/zone/settings/development_mode'
require 'cloudflair/api/zone/settings/email_obfuscation'
require 'cloudflair/api/zone/settings/hotlink_protection'
require 'cloudflair/api/zone/settings/ip_geolocation'
require 'cloudflair/api/zone/settings/ipv6'
require 'cloudflair/api/zone/settings/minify'
require 'cloudflair/api/zone/settings/mirage'
require 'cloudflair/api/zone/settings/mobile_redirect'
require 'cloudflair/api/zone/settings/origin_error_page_pass_thru'
require 'cloudflair/api/zone/settings/polish'
require 'cloudflair/api/zone/settings/prefetch_preload'
require 'cloudflair/api/zone/settings/response_buffering'
require 'cloudflair/api/zone/settings/rocket_loader'
require 'cloudflair/api/zone/settings/security_header'
require 'cloudflair/api/zone/settings/security_level'
require 'cloudflair/api/zone/settings/server_side_exclude'
require 'cloudflair/api/zone/settings/sort_query_string_for_cache'
require 'cloudflair/api/zone/settings/ssl'
require 'cloudflair/api/zone/settings/tls_client_auth'
require 'cloudflair/api/zone/settings/tls_1_2_only'
require 'cloudflair/api/zone/settings/tls_1_3'
require 'cloudflair/api/zone/settings/true_client_ip_header'
require 'cloudflair/api/zone/settings/waf'
require 'cloudflair/api/zone/settings/websockets'
